name: CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        wget https://github.com/fmtlib/fmt/releases/download/8.1.1/fmt-8.1.1.zip
        unzip fmt-8.1.1.zip
        cd fmt-8.1.1
        mkdir build
        cd build
        cmake ..
        make fmt -j 10
        sudo make install
    - name: cmake build
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: cmake make
      run: cmake --build build --parallel 3
    - name: test
      run: ./build/aixlog_example
    - name: test fmt
      run: ./build/aixlog_fmt_example


  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
        vcpkg.exe install fmt --triplet x64-windows
    - name: cmake build
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET="x64-windows" -DCMAKE_BUILD_TYPE=Release
    - name: cmake make
      run: cmake --build build --parallel 3
    - name: test
      run: build\Debug\aixlog_example.exe
    - name: test fmt
      run: build\Debug\aixlog_fmt_example.exe


  macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: brew install fmt
    - name: cmake build
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: cmake make
      run: cmake --build build --parallel 3
    - name: test
      run: ./build/aixlog_example
    - name: test fmt
      run: ./build/aixlog_fmt_example
